---
  - name: install needed packages
    yum: name={{item}} state=installed
    with_items:
      - rubygems

  - name: Copy Gemfile
    action: template src=Gemfile dest=/home/{{user}}/Gemfile owner={{user}}

  - name: Copy gem install script
    action: template src=install.sh dest=/home/{{user}}/install.sh mode="u=wrx" owner={{user}}

  - stat: path=/etc/profile.d/rvm.sh
    register: rvm_folder

  - name: install rvm
    shell: "curl -sSL https://get.rvm.io | bash"
    when: rvm_folder.stat.isdir is not defined

  - name: install bundler
    gem: name=bundler

  - name: get vagrant
    shell: wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb

  - name: install vagrant
    shell: sudo dpkg -i vagrant_1.7.4_x86_64.deb

  - name: remove vagrant distro file
    file: name=/home/{{user}}/vagrant_1.7.4_x86_64.deb state=absent

  - name: Set up .bashrc to display current git branch
    action: template src=bashrc dest=/home/{{user}}/.bashrc mode="u=wr" owner={{user}}
