---
  - name: install needed packages
    yum: name={{item}} state=installed
    with_items:
      - rubygems

  - name: Copy Gemfile
    copy: src=Gemfile dest=/home/{{user}}/Gemfile owner={{user}} group={{user}}

  - name: Copy gem install script
    copy: src=install.sh dest=/home/{{user}}/install.sh mode="u=wrx" owner={{user}} group={{user}}

  - stat: path=/etc/profile.d/rvm.sh
    register: rvm_folder

  - name: install rvm
    shell: "curl -sSL https://get.rvm.io | bash"
    when: rvm_folder.stat.isdir is not defined

  - name: install bundler
    gem: name=bundler

  - name: See if Vagrant is installed
    shell: "dpkg -l | grep vagrant"
    ignore_errors: true
    register: vagrant_installed

  - name: See if we have Vagrant
    stat: path=/home/{{user}}/vagrant_1.7.4_x86_64.deb
    register: vagrant_downloaded
    when: vagrant_installed.rc == 1

  - name: Get vagrant if needed
    get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb dest=/home/{{user}} mode=0440
    when: vagrant_installed.rc == 1 and not vagrant_downloaded.stat.exists

  - name: Install vagrant if needed
    shell: sudo dpkg -i /home/{{user}}/vagrant_1.7.4_x86_64.deb
    when: vagrant_installed.rc == 1

  - name: Set up .bashrc to display current git branch
    copy: src=bashrc dest=/home/{{user}}/.bashrc mode="u=wr" owner={{user}} group={{user}}
