---
  - name: 2.1.1 Remove telnet-server (Scored)
    yum: >
      name=telnet-server
      state=absent

  - name: 2.1.2 Remove telnet Clients (Scored)
    yum: >
      name=telnet
      state=absent

  - name: 2.1.3 Remove rsh-server (Scored)
    yum: >
      name=rsh-server
      state=absent

  - name: 2.1.4 Remove rsh (Scored)
    yum: >
      name=rsh
      state=absent

  - name: 2.1.5 Remove NIS Client (Scored)
    yum: > 
      name=ypbind
      state=absent

  - name: 2.1.6 Remove NIS Server (Scored)
    yum: >
      name=ypserv
      state=absent

  - name: 2.1.7 Remove tftp (Scored)
    yum: >
      name=tftp
      state=absent

  - name: 2.1.8 Remove tftp-server (Scored)
    yum: >
      name=tftp-server
      state=absent

  - name: 2.1.9 Remove talk (Scored)
    yum: >
      name=talk
      state=absent

  - name: 2.1.10 Remove talk-server (Scored)
    yum: >
      name=talk-server
      state=absent

  - name: 2.1.12 Disable chargen-dgram (check if exists)
    stat: path=/etc/xinetd.d/chargen-dgram
    register: chargen_dgram

  - name: 2.1.12 Disable chargen-dgram (disable xinetd service)
    service: >
        name=chargen-dgram
        state=stopped
        enabled=no
    when: chargen_dgram.stat.exists

  - name: 2.1.13 Disable chargen-stream (check if exists) (Scored)
    stat: path=/etc/xinetd.d/chargen-stream
    register: chargen_stream

  - name: 2.1.13 Disable chargen-stream (disable xinetd service) (Scored)
    service: >
        name=chargen-stream
        state=stopped
        enabled=no
    when: chargen_stream.stat.exists

  - name: 2.1.14 Disable daytime-dgram (check if exists) (Scored)
    stat: path=/etc/xinetd.d/daytime-dgram
    register: daytime_dgram

  - name: 2.1.14 Disable daytime-dgram (disable xinetd service) (Scored)
    service: >
        name=daytime-dgram
        state=stopped
        enabled=no
    when: daytime_dgram.stat.exists

  - name: 2.1.15 Disable daytime-stream (check if exists) (Scored)
    stat: path=/etc/xinetd.d/daytime-stream
    register: daytime_stream

  - name: 2.1.15 Disable daytime-stream (disable xinetd service) (Scored)
    service: >
        name=daytime-stream
        state=stopped
        enabled=no
    when: daytime_stream.stat.exists

  - name: 2.1.16 Disable echo-dgram (check if exists) (Scored)
    stat: path=/etc/xinetd.d/echo-dgram
    register: echo_dgram

  - name: 2.1.16 Disable echo-dgram (disable xinetd service) (Scored)
    service: >
        name=echo-dgram
        state=stopped
        enabled=no
    when: echo_dgram.stat.exists

  - name: 2.1.17 Disable echo-stream (check if exists) (Scored)
    stat: path=/etc/xinetd.d/echo-stream
    register: echo_stream

  - name: 2.1.17 Disable echo-stream (disable xinetd service) (Scored)
    service: >
        name=echo-stream
        state=stopped
        enabled=no
    when: echo_stream.stat.exists

  - name: 2.1.18 Disable tcpmux-server (check if exists) (Scored)
    stat: path=/etc/xinetd.d/tcpmux-server
    register: tcpmux_server

  - name: 2.1.18 Disable tcpmux-server (disable xinetd service) (Scored)
    service: >
        name=tcpmux-server
        state=stopped
        enabled=no
    when: tcpmux_server.stat.exists

  - name: 2.1.11 Remove xinetd (Scored)
    yum: >
      name=xinetd
      state=absent

  - name: 3.1 Set Daemon umask (Scored)
    lineinfile: >
      dest=/etc/sysconfig/init
      state=present
      regexp=^umask
      line="umask 027"

  - name: 3.2 Remove X Windows (runlevel 3) (Scored)
    lineinfile: >
      dest=/etc/inittab
      state=present
      regexp="^id:"
      line="id:3:initdefault:"

  - name: 3.2 Remove X Windows (remove package group) (Scored)
    yum: >
      name=xorg-x11-server-common
      state=absent

  - name: 3.3 Disable Avahi Server (check if installed) (Scored)
    stat: path=/etc/init.d/avahi-daemon
    register: avahi_service

  - name: 3.3 Disable Avahi Server (disable service) (Scored)
    service: >
      name=avahi-daemon
      state=stopped
      enabled=no
    when: avahi_service.stat.exists

  - name: 3.4 Check to see if cups daemon is installed (Not Scored)
    stat: path=/etc/init.d/cups
    register: cups_service

  - name: 3.4 Disable Print Server - CUPS (Not Scored)
    service: >
      name=cups
      state=stopped
      enabled=no
    ignore_errors: yes
    when: cups_service.stat.exists

  - name: 3.5 Remove DHCP Server (Scored)
    yum: >
      name=dhcp
      state=absent

  - name: 3.6 Configure Network Time Protocol (ipv4) (Scored)
    yum: >
      pkg=ntp
      state=installed
    always_run: yes

  - name: 3.6 Configure Network Time Protocol (ipv4) (Scored)
    service: >
      name=ntpd
      state=started
      enabled=yes

  - name: 3.6 Configure Network Time Protocol (ipv4) (Scored)
    lineinfile: >
      dest=/etc/ntp.conf
      state=present
      regexp="^restrict default"
      line="restrict default kod nomodify notrap nopeer noquery"
      insertafter=EOF

  - name: 3.6 Configure Network Time Protocol (ipv6) (Scored)
    lineinfile: >
      dest=/etc/ntp.conf
      state=present
      regexp="^restrict -6 default"
      line="restrict -6 default kod nomodify notrap nopeer noquery"
      insertafter=EOF

  - name: 3.9 Remove DNS Server (Not Scored)
    yum: >
      name=bind
      state=absent

  - name: 3.10 Remove FTP Server (Not Scored)
    yum: >
      name=vsftpd
      state=absent

  - name: 3.12 Remove Dovecot (IMAP and POP3 services) (Not Scored)
    yum: >
      name=dovecot
      state=absent

  - name: 3.13 Remove Samba (Not Scored)
    yum: >
      name=samba
      state=absent

  - name: 3.14 Remove HTTP Proxy Server (Not Scored)
    yum: >
      name=squid
      state=absent

  - name: 3.15 Remove SNMP Server (Not Scored)
    yum: >
      name=net-snmp
      state=absent

  - name: 3.16 Configure Mail Transfer Agent for Local-Only Mode (Scored)
    yum: >
      name=postfix
      state=present

  - name: 3.16 Configure Mail Transfer Agent for Local-Only Mode (Scored)
    lineinfile: >
      backup=yes
      state=present
      dest=/etc/postfix/main.cf
      backrefs=yes
      regexp="^inet_interfaces"
      line="inet_interfaces = localhost"
    ignore_errors: yes
