---
  - name: install dev packages
    yum: name={{item}} state=installed
    with_items:
      - git
      - ansible
      - vim
      - gcc-c++
      - patch
      - readline
      - readline-devel
      - zlib
      - zlib-devel
      - libyaml-devel
      - libffi-devel
      - openssl-devel
      - make
      - bzip2
      - autoconf
      - automake
      - libtool
      - bison
      - ruby-devel
      - libxml2
      - libxml2-devel
      - libxslt
      - libxslt-devel
      - wget
      - dpkg
      - java-1.7.0-openjdk
      - java-1.7.0-openjdk-devel

  - name: Create the deploy user
    user: name={{user}} comment="deploy user" generate_ssh_key=yes ssh_key_bits=2048 state=present password={{password}} shell=/bin/bash

  - name: Copy ssh keys to the user's .ssh directory
    action: template src=ssh_keys.pub dest=/home/{{user}}/.ssh/authorized_keys mode=0700 owner={{user}}

  - name: Set {{user}} as sudoer
    lineinfile: dest=/etc/sudoers line="{{user}} ALL=(ALL) NOPASSWD ":" ALL"

  - name: remove ubuntu's user
    user: name=ubuntu state=absent remove=yes

  - name: Set vi preferences
    action: template src=vimrc dest=/home/{{user}}/.vimrc owner={{user}}

  - name: Clear dpkg
    shell: dpkg --clear-avail
    sudo: true
